### ISSUE TITLE
Type must be marked with ZeroFormattableAttribute. Object

### ISSUE THREAD

**Issue by Symbai** [neuecc/ZeroFormatter#102]
[Index(1)]
        public virtual object Value { get; set; }

Says "Type must be marked with ZeroFormattableAttribute. Object"

        [Index(1)]
        [ZeroFormattable]
        public virtual object Value { get; set; }

Says "Attribute 'ZeroFormattable' is not valid on this declaration type. It is only valid on 'class, struct' declarations." But Value is not a class nor a struct. Its a .NET primitive type (i.e. can be byte, short, int, string)

**Comment by Ujang360** [comment]
`[ZeroFormattable]` attribute valid only on class/struct declaration. In your example, you've mark the property of a class/struct with `[ZeroFormattable]` attribute which is wrong.

Example:
```
[ZeroFormattable]
public class SomeClass
{
    [Index(0)]
    public virtual object Value { get; set; }
}
```

**Comment by Symbai** [comment]
That's how I had in first case but Zeroformatter raises the exception above then. It looks like its getting confused by the object property and thinks its a class or struct instead of .NET type 'object'.
