### ISSUE TITLE
Error: Bad IL format. Please support .NET Core 3.0, 3.1

### ISSUE THREAD

**Issue by CRC32EX** [neuecc/ZeroFormatter#112]
# Steps to reproduce this issue
### 1. Write code
```cs
// Program.cs
using System;
using ZeroFormatter;

namespace ZeroFormatterTest
{
  [ZeroFormattable]
  public class MyClass
  {
    [Index(0)]
    public virtual int Age { get; set; }
  }

  class Program
  {
    static void Main(string[] args)
    {
      var mc = new MyClass { Age = 1 };
      ZeroFormatterSerializer.Serialize(mc);
    }
  }
}
```

### 2. Execute
```txt
$ dotnet run
Unhandled exception. System.BadImageFormatException: Bad IL format.
  at ZeroFormatter.DynamicObjectSegments.ZeroFormatter_Formatters_DefaultResolver.ZeroFormatterTest.MyClass$Formatter.Serialize(Byte[]& , Int32 , MyClass )
  at ZeroFormatter.ZeroFormatterSerializer.CustomSerializer`1.Serialize[T](Byte[]& buffer, Int32 offset, T obj)
  at ZeroFormatter.ZeroFormatterSerializer.CustomSerializer`1.Serialize[T](T obj)
  at ZeroFormatter.ZeroFormatterSerializer.Serialize[T](T obj)
  at ZeroFormatterTest.Program.Main(String[] args) in C:\Programs\VC\ZeroFormatterTest\ZeroFormatterTest\Program.cs:line 20
```

### Possible solution
- use `.NET Core 2.2`, instead of `.NET Core 3.0`
- use `.NET Core 2.2`, instead of `.NET Core 3.1`

# Environment
- Windows 10 64bit 1903 (Build 18362.30)
- .NET Core 3.0.100
- .NET Core 3.1.100
- ZeroFormatter 1.6.4
- Visual Studio Community 2019

**Comment by btogkas** [comment]
In order to fix this you will need to change 
DynamicFormatter.cs
private static void CreateSerialize(Type elementType, ....formattersInField)

....
// if(segment != null)
...
il.Emit(OpCodes.Call, typeof(IZeroFormatterSegment).GetTypeInfo().GetMethod("Serialize"));

to 

il.Emit(OpCodes.Callvirt, typeof(IZeroFormatterSegment).GetTypeInfo().GetMethod("Serialize"));

**Comment by enshivam** [comment]
+1

**Comment by roikra** [comment]
Any progress regarding this issue? I am also struggling with it.

**Comment by btogkas** [comment]
The solution is above. You have to get the code and On DynamicFormatter.cs
you have to change OpCodes.Call to OpCodes.Callvirt on the line i have posted. Unfortunately i have not the right to pr - merge.

**Comment by roikra** [comment]
Can we open a PR?

**Comment by roikra** [comment]
CreateSerialize does not exist in CreateSerialize. 
Are you referring to the NetCore project?

**Comment by truecooler** [comment]
> CreateSerialize does not exist in CreateSerialize.
> Are you referring to the NetCore project?

@roikra
check it out [here](https://github.com/neuecc/ZeroFormatter/blob/4274946b1b595b1c8bd395f7b368bbb674ec8029/src/ZeroFormatter/Formatters/DynamicFormatter.cs#L301)
works fine with .net core 3

**Comment by OvsyannikovAA** [comment]
> 
> 
> > CreateSerialize does not exist in CreateSerialize.
> > Are you referring to the NetCore project?
> 
> @roikra
> check it out [here](https://github.com/neuecc/ZeroFormatter/blob/4274946b1b595b1c8bd395f7b368bbb674ec8029/src/ZeroFormatter/Formatters/DynamicFormatter.cs#L301)
> works fine with .net core 3

This solution doesn't work for me.

**Comment by OvsyannikovAA** [comment]
> 
> 
> CreateSerialize does not exist in CreateSerialize.
> Are you referring to the NetCore project?

In method:

 static TypeInfo BuildFormatter(ModuleBuilder builder, Type resolverType, Type elementType, Tuple<int, EmittableMemberInfo>[] memberInfos)

You must change line:

il.Emit(OpCodes.Call, typeof(IZeroFormatterSegment).GetTypeInfo().GetMethod("Serialize"));

To:

il.Emit(OpCodes.Callvirt, typeof(IZeroFormatterSegment).GetTypeInfo().GetMethod("Serialize"));

**Comment by balendra-singh** [comment]
@btogkas  The above solution works if the above changes are done on both the projects

1. **ZeroFormatter**
2. **ZeroFormatter.NETCore**

Cheers!

**Comment by CRC32EX** [comment]
This issue was resolved.
Install this package.
```ps1
Install-Package Alexinea.ZeroFormatter
```

https://github.com/alexinea/Alexinea.ZeroFormatter/

**Comment by romeshniriella** [comment]
> This issue was resolved.
> Install this package.
> 
> ```powershell
> Install-Package Alexinea.ZeroFormatter
> ```
> 
> https://github.com/alexinea/Alexinea.ZeroFormatter/

Lifesaver! Thank you.

**Comment by perennialmind** [comment]
> > This issue was resolved.
> > Install this package.
> > ```powershell
> > Install-Package Alexinea.ZeroFormatter
> > ```
> > https://github.com/alexinea/Alexinea.ZeroFormatter/
> 
> Lifesaver! Thank you.

It looks like that fork changed the wire format of DateTime from (seconds,nanos) to (ticks) - without updating any docs. 
https://github.com/neuecc/ZeroFormatter/compare/master...alexinea:master#diff-e09fd40df61d89d615fe9be86f2da4ed8ec5d79e04e7b57cb0b92265bc838525L581
