### ISSUE TITLE
can we have a nuget icon?

### ISSUE THREAD

**Issue by SimonCropp** [neuecc/ZeroFormatter#35]

**Comment by neuecc** [comment]
Currently, ZeroFormatta have no icon.
But yes, I want to icon:)

**Comment by neuecc** [comment]
Thank you, `NServiceBus.ZeroFormatter`.
https://github.com/SimonCropp/NServiceBus.ZeroFormatter

**Comment by neuecc** [comment]
@SimonCropp sorry, can you update NuGet's ZeroFormatter dependency to `1.4.1`? `1.4.0` has bugs...

**Comment by SimonCropp** [comment]
@neuecc updated to 1.4.1. and thanks for the heads up

thenounproject is a good source of icons. they have a variety of licenses. i picked a random on for NServiceBus.ZeroFormatter: http://thenounproject.com/term/Astronaut/337063/

**Comment by neuecc** [comment]
Thank you very much!
