### ISSUE TITLE
zfc.exe -n flag does not add namespace import for ZeroFormatter

### ISSUE THREAD

**Issue by yunspace** [neuecc/ZeroFormatter#53]
If I run:

    zfc -i Assembly-CSharp.csproj -o Assets/Scripts/Models/Generated.cs

Everything works fine because the generated files belong to default `ZeroFormatter` namespace. But if I run zfc with custom namespace:

    zfc -i Assembly-CSharp.csproj -o Assets/Scripts/Models/Generated.cs -n Models

Then I would get multiple import errors for `ZeroFormatter.DirtyTracker` etc, because the generate file under custom namespace `Models` is missing `using ZeroFormatter;` at the top. 

Of course this can be easily worked around by adding the import statement in. But probably best to fix it in the code generator.

**Comment by neuecc** [comment]
Thank you.
Yes!
I've already fixed but not yet released. https://github.com/neuecc/ZeroFormatter/commit/b74b58065eb4f645d4bd6d47b0b3a167317509ed
I'll release fix update soon.

**Comment by neuecc** [comment]
released ver 1.6.1. https://github.com/neuecc/ZeroFormatter/releases/tag/1.6.1
