### ISSUE TITLE
unity 4.7.1 standalone build

### ISSUE THREAD

**Issue by sosan** [neuecc/ZeroFormatter#58]
im using unity 4.7.1 and i was using zeroformater version 1.6.1. for register i cannot use 'RuntimeInitializeOnLoad' because in unity 4.7.1 not exist, so i was called on awake() to register formatats, and worked pretty well on editor and pc standalone build. i updated zeroformater to version 1.6.2 and im still calling it form awake() to register formats, work on editor but not in pc standalone build.

in new version i read that i must use: [SetUp]..... 
i tried but unity cannot be found it. 
Best regards.

**Comment by neuecc** [comment]
You can use `-u` option for don't generate `RuntimeInitializeOnLoad`.
and manually call `ZeroFormatterInitializer.Register()` on your startup code.

`[Setup]` is only for Unit Tests Runner(from Unity 5.3).

**Comment by sosan** [comment]
thank you :)
