### ISSUE TITLE
zfc generated file does empty at my sample project. "InvalidOperationException: Type is not supported, please register"

### ISSUE THREAD

**Issue by yoonhwan** [neuecc/ZeroFormatter#94]
How to generate ZeroFormatterInitializer.cs file to use zfc.exe?

ZeroFormatter version : ver 1.6.4

my sample code

[Sample.cs]
```csharp
[ZeroFormattable]
public class SomeMessage {
	[Index(0)]
	public virtual int SomeInt { get; set; }
}
public class Sample : MonoBehaviour {
	void Start () {
		var mc = new SomeMessage
		{
			SomeInt = 999
		};
		var bytes = ZeroFormatterSerializer.Serialize(mc);
		var mc2 = ZeroFormatterSerializer.Deserialize<SomeMessage>(bytes);
		Debug.Log(mc2.SomeInt);
	}
}
```
[Assembly-CSharp.csproj]
```xml
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<...>
<ItemGroup>
    <Compile Include="Assets\Script\Sample.cs" />
    <Reference Include="UnityEngine.UI">
<...>
</ItemGroup>
<...>
</Project>
```

[command line]
```shell
zfc.exe -i "Assembly-CSharp.csproj" -s -o "Assets\Plugins\ZeroFormatter"
```

Execute this script with zfc.exe but output generated code is empty.
What's wrong in my generate zeroformatter prebuild script using by zfc.exe??
please check my code. i really need to test and use zeroformatter.

[ZeroFormatterInitializer.cs]
```csharp
#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
namespace Sample
{
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::ZeroFormatter.Formatters;
    using global::ZeroFormatter.Internal;
    using global::ZeroFormatter.Segments;
    using global::ZeroFormatter.Comparers;

    public static partial class ZeroFormatterInitializer
    {
        static bool registered = false;

        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
        public static void Register()
        {
            if(registered) return;
            registered = true;
            // Enums
            // Objects
            // Structs
            // Unions
            // Generics
        }
    }
}
#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612
```

**Comment by yoonhwan** [comment]
i think class is not generate type.

If so, how can i pass this error? 

this is Unity runtime console error log
```csharp
InvalidOperationException: Type is not supported, please register SomeMessage
ZeroFormatter.Formatters.ErrorFormatter`2[TTypeResolver,T].Serialize (System.Byte[]& bytes, System.Int32 offset, T value) (at <1c2cf38bb8ea407ea801af930792b503>:0)
ZeroFormatter.ZeroFormatterSerializer+CustomSerializer`1[TTypeResolver].Serialize[T] (System.Byte[]& buffer, System.Int32 offset, T obj) (at <1c2cf38bb8ea407ea801af930792b503>:0)
ZeroFormatter.ZeroFormatterSerializer+CustomSerializer`1[TTypeResolver].Serialize[T] (T obj) (at <1c2cf38bb8ea407ea801af930792b503>:0)
ZeroFormatter.ZeroFormatterSerializer.Serialize[T] (T obj) (at <1c2cf38bb8ea407ea801af930792b503>:0)
Sample.Start () (at Assets/Script/Sample.cs:23)
```


SomeMessage...
Do I have to register myself? or Does zfc.exe generate code handle the task instead?

help me~

**Comment by majorika** [comment]
-s option does not seem to work. try it without the -s option.
or you can fix below lines.

https://github.com/neuecc/ZeroFormatter/blob/master/src/ZeroFormatter.CodeGenerator/Program.cs#L160 to 

`foreach (var item in objectGen.SelectMany(x => x.Types, (g, t) => new ObjectSegmentType { Name = t.Name, FullName = t.FullName, LastIndex = t.LastIndex, Properties = t.Properties, Namespace = g.Namespace }))`

https://github.com/neuecc/ZeroFormatter/blob/master/src/ZeroFormatter.CodeGenerator/Program.cs#L167 to

`foreach (var item in structGen.SelectMany(x => x.Types, (g, t) => new ObjectSegmentType { Name = t.Name, FullName = t.FullName, LastIndex = t.LastIndex, Properties = t.Properties, Namespace = g.Namespace }))
`
https://github.com/neuecc/ZeroFormatter/blob/master/src/ZeroFormatter.CodeGenerator/Program.cs#L174 to

`foreach (var item in unionGen.SelectMany(x => x.Types, (g, t) => new UnionType { Name = t.Name, FullName = t.FullName, FallbackTypeName = t.FallbackTypeName, SubTypeNames = t.SubTypeNames, UnionKeyPropertyName = t.UnionKeyPropertyName, UnionKeyTypeName = t.UnionKeyTypeName, Namespace = g.Namespace }))
`

**Comment by yoonhwan** [comment]
@majorika 
thank you for your reply. I try running zfc.exe without -s option. but
ZeroFormatterInitialize.cs is empty as before. and I think your modify 
code is going to solve it(-s option).

I think this problem currently not  ZeroFormatterInitialize.cs. can you
check my second comment? my SomeMessage can't serialize at 
Unity ZeroFormatter. My SomeMessage class must to be Set or Register 
in ZeroFormatterInitialize.cs? 


*ZeroFormatterInitialize.cs file is zfx.exe generated code

**Comment by majorika** [comment]
you should remove ZeroFormatterInitialize.cs first.
and run zfc.exe without -s option, and -o option with specific a file name, not a path.
ex) `zfc.exe -i "Assembly-CSharp.csproj" -o "Assets\Plugins\Generated.cs"`

**Comment by yoonhwan** [comment]
I found solution this problem. Record for someone who is 
experiencing the same problem as me. 

Simply put, This was a configuration issue in the csproj file.
The reason I am having this problem is that my working env
-ironment is moving between mac and windows. 

I also use vscode. vscode does not correct the csproj file to
normal. So I corrected the csproj file manually and the probl
-em is solved. The Generation cs file has been created successfully.

Also, the problem is that the zfc tool does not detect problems
with the csproj file. 

Here is some example with csproj file modification. 

[Problem code]
```csharp
[ZeroFormattable]
public class SomeMessage {
	[Index(0)]
	public virtual int SomeInt { get; set; }
}
```
```xml
<ItemGroup>
    <None Include="App.config" />
    <Reference Include="System.Core" />
     <Reference Include="ZeroFormatter">
     <HintPath>/Project/GlobalProject/ZeroFomatter/Assets/Plugins/ZeroFormatter/ZeroFormatter.dll</HintPath>
     </Reference>
     <Reference Include="ZeroFormatter.Interfaces">
     <HintPath>/Project/GlobalProject/ZeroFomatter/Assets/Plugins/ZeroFormatter/ZeroFormatter.Interfaces.dll</HintPath>
     </Reference>
  </ItemGroup>
```
The generate code(**.cs) is not contain the SomeMessage class. and
does not registered in ZeroFormatterInitializer.Register() function. 


[Solve code]
```csharp
[ZeroFormattable]
public class SomeMessage {
	[Index(0)]
	public virtual int SomeInt { get; set; }
}
```
```xml
<ItemGroup>
    <None Include="App.config" />
    <Reference Include="System.Core" />
    <Reference Include="ZeroFormatter">
      <HintPath>F:\Projects\ZeroFormatter\Assets\Sandbox\libs\ZeroFormatter.dll</HintPath>
    </Reference>
    <Reference Include="ZeroFormatter.Interfaces">
      <HintPath>F:\Projects\ZeroFormatter\Assets\Sandbox\libs\ZeroFormatter.Interfaces.dll</HintPath>
    </Reference>
  </ItemGroup>
```

I manually set the dll path. The SomeMessage class added in generate code
and Register nomally. 

If you are developing on the Windows platform and using visual studio. I do not think this problem will come out. This is because the csproj file is normally modified and compiled.
thank you.


ps. 
@majorika says that when you set the -s option and put the folder name, the file name that is automatically generated is ZeroFormatterInitialize.cs. However, you should be aware that the ZeroFormatterInitialize.cs name mentioned here is the same cs file name, except for the -s option.

Thank you @majorika for your help.
